//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConversationList
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public int IdConversations { get; set; }
        public bool IsConfirm { get; set; }
        public bool IsRead { get; set; }
        public System.DateTime DateTimeRead { get; set; }
        public string UserId { get; set; }
        public Nullable<int> ConversationId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Conversation Conversation { get; set; }
    }
}
