//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Help
    {
        public int Id { get; set; }
        public string file { get; set; }
        public string Mess { get; set; }
        public System.DateTime time { get; set; }
        public string Username { get; set; }
    }
}
