//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Job()
        {
            this.JobDetails = new HashSet<JobDetail>();
            this.Qr_Patrol = new HashSet<Qr_Patrol>();
        }
    
        public int Id { get; set; }
        public string NameLocation { get; set; }
        public string subAdministrativeArea { get; set; }
        public string UserCreate { get; set; }
        public bool status { get; set; }
        public Nullable<System.DateTime> TimeDelete { get; set; }
        public string Location_X { get; set; }
        public string Location_Y { get; set; }
        public string administrativeArea { get; set; }
        public string country { get; set; }
        public System.DateTime TimeCreate { get; set; }
        public string street { get; set; }
        public string UserDelete { get; set; }
        public int IdDepartment { get; set; }
        public Nullable<int> DepartmentId { get; set; }
    
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobDetail> JobDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Qr_Patrol> Qr_Patrol { get; set; }
    }
}
