//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messenger
    {
        public int Id { get; set; }
        public string Contents { get; set; }
        public System.DateTime SentAt { get; set; }
        public bool IsRead { get; set; }
        public int idConversation { get; set; }
        public Nullable<int> ConversationId { get; set; }
        public int TypeMess { get; set; }
        public string Username { get; set; }
        public string filename { get; set; }
    
        public virtual Conversation Conversation { get; set; }
    }
}
