//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class notification
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Username { get; set; }
        public System.DateTime Time { get; set; }
        public bool Status { get; set; }
        public string Message { get; set; }
        public string Token { get; set; }
    }
}
