//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfileUser
    {
        public string Id { get; set; }
        public string imageName { get; set; }
        public string birtDate { get; set; }
        public string placeOfBirt { get; set; }
        public string placeOfOrigin { get; set; }
        public string curResidence { get; set; }
        public string resident { get; set; }
        public string temResidence { get; set; }
        public string gender { get; set; }
        public string taxCode { get; set; }
        public string marital { get; set; }
        public string ethnicity { get; set; }
        public string religion { get; set; }
        public string nationality { get; set; }
        public string educationalLevel { get; set; }
        public string otherNum { get; set; }
        public string address { get; set; }
        public string zalo { get; set; }
        public string CCCD { get; set; }
        public string imageFrontCCCD { get; set; }
        public string imageBackCCCD { get; set; }
        public string passPortNum { get; set; }
        public string codeBank { get; set; }
        public string numBank { get; set; }
        public string nameAccountBank { get; set; }
    }
}
