//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Qr_Patrol
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Qr_Patrol()
        {
            this.User_Check_Patrol = new HashSet<User_Check_Patrol>();
        }
    
        public int Id { get; set; }
        public string code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Location_X { get; set; }
        public string Location_Y { get; set; }
        public int id_Job { get; set; }
        public int time_Check { get; set; }
        public string path_Qr { get; set; }
        public Nullable<int> JobId { get; set; }
    
        public virtual Job Job { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Check_Patrol> User_Check_Patrol { get; set; }
    }
}
