//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resignation
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public System.DateTime datetimeResignation { get; set; }
        public System.DateTime datetimeWrite { get; set; }
        public string messenger { get; set; }
        public string Phone { get; set; }
        public bool IsConfim { get; set; }
    }
}
