//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Check_Patrol
    {
        public int Id { get; set; }
        public int QrCheck { get; set; }
        public int id_Job { get; set; }
        public string Username_Check { get; set; }
        public System.DateTime Time_Check { get; set; }
        public string location_X_Check { get; set; }
        public string location_Y_Check { get; set; }
        public bool Is_Confim { get; set; }
        public int isLocation { get; set; }
        public string Mess { get; set; }
        public string ImagePath { get; set; }
        public string imageName { get; set; }
        public System.DateTime TimeConfim { get; set; }
        public string UserConfim { get; set; }
        public Nullable<int> Qr_PatrolId { get; set; }
    
        public virtual Qr_Patrol Qr_Patrol { get; set; }
    }
}
